name: Cypress wsplus API
on:
    pull_request:
        branches: [master]

jobs: 
    cypress-run:
        runs-on: windows-latest
        steps: 
            - name: Clone repository
              uses: actions/checkout@v4
            - name: Cypress run
              uses: cypress-io/github-action@v6
